build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ColorTurbine/ColorTurbine .
    - docker run registry.gitlab.com/ColorTurbine/ColorTurbine dotnet test /ColorTurbine.tests/ColorTurbine.tests.csproj
    - docker push registry.gitlab.com/ColorTurbine/ColorTurbine:latest
  only:
    - master