stages:
  - build_nuget
  - deploy_nuget
  - build_docker
  - deploy_docker

build_image:
  image: docker:git
  stage: build_docker
  services:
    - docker:dind
  script:
    - docker build -t build-sdk .
    - docker run --name built -t build-sdk dotnet test ColorTurbine.Tests/ColorTurbine.Tests.csproj
    - docker cp built:/app app/
  artifacts:
    name: "${CI_COMMIT_REF_NAME}"
    paths:
      - app/

deploy_image:
  image: docker:git
  stage: deploy_docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/colorturbine/colorturbine:latest -f deploy.Dockerfile .
    - docker push registry.gitlab.com/colorturbine/colorturbine:latest
  only:
    - master

build:
  image: microsoft/dotnet:2.1-sdk
  stage: build_nuget
  script:
    - dotnet build ColorTurbine -c Release -o "${PWD}/artifacts/"
    - dotnet build ColorTurbine.Framework -c Release -o "${PWD}/artifacts/"
    - dotnet build ColorTurbine.Tests -c Release -o "${PWD}/artifacts/"
    - dotnet test ColorTurbine.Tests/ColorTurbine.Tests.csproj
  artifacts:
    expire_in: 31d
    paths:
      - artifacts/*

deploy_master:
  image: microsoft/dotnet:2.1-sdk
  stage: deploy_nuget
  script:
    - dotnet pack ColorTurbine.Framework --version-suffix beta -c Release -o "${PWD}/artifacts/"
    - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "${nuget_api_key}" "${PWD}/artifacts/*.nupkg"
  artifacts:
    paths:
      - artifacts/*
  only:
    - master
